### ISSUE TITLE
Contributor Agreement

### ISSUE THREAD

**Issue by pschorf** [aredington/parallel-test#1]
Hi, is there a contributor agreement required to submit patches to the project since it is under the EPL?

**Comment by aredington** [comment]
Hi @pschorf ,

I do not require a CA for contributions to parallel-test, please feel free to open pull requests.

Your contributions will be made under the terms of the EPL, and my use of your contributions as part of parallel-test will be likewise governed by the EPL. As I am not attempting to exert copyrights or other rights over this work, my understanding is that no contributor agreement will be required.

The parallel-test plugin makes use of source code from other EPL licensed projects such as Clojure the language and Leiningen, hence its license as EPL. If I was willing to cut the project from whole cloth I'd have probably licensed it MIT or otherwise similarly less restrictive than EPL.

**Comment by pschorf** [comment]
Thanks!
